### ISSUE TITLE
Implement changing user & group with names

### ISSUE THREAD

**Issue by vorner** [vorner/spirit#19]
Currently, only changing with an uid/gid is implemented. Using `privdrop` should help with switching by name.

**Comment by myrrlyn** [comment]
I am willing to take this issue. `nix` does not provide a safe wrapper for `libc::getpwnam`, which seems to be the appropriate function to map a textual username to a system UID. Therefore, I will need to relax the `#![forbid(unsafe_code)]` constraint in order for work to progress.

**Comment by myrrlyn** [comment]
Tracking branch: https://github.com/myrrlyn/spirit/tree/feature/19

**Comment by vorner** [comment]
Thank you! It looks good, so could you clean up the history a bit (I don't think the intermediate steps are needed here, though I won't stop you if you prefer the real history instead of „optimised“ one) and make a pull request? Also, I think the documentation at the lib level mentions this is not implemented yet ‒ that note should be removed.

As for tests… I'm afraid testing this kind of thing is tricky and will require non-trivial setup. The test itself must be able to run as root, have some specific user it knows in the system, so it sounds like having to launch it inside some docker or something like that. But I've checked it manually, so let's say we get the functionality in first and think about tests for the crate in general ‒ there's a lot of hard stuff to test here.
