### ISSUE TITLE
Ability to pass a Struct as the default config

### ISSUE THREAD

**Issue by j-a-m-l** [vorner/spirit#35]
Maybe I'm missing something, but it looks like it's mandatory to pass a TOML string to `config_defaults`.

Is there a way to pass a `Struct` directly to `ConfigBuilder`?

**Comment by vorner** [comment]
You're right, currently only TOML string is accepted. I'll explain more how the thing works internally:

* On every load, multiple configuration files or other sources are loaded and stacked ‒ the one on top overwrites options in lower ones.
* The one passed in by `config_defaults` is used as the bottom layer, if provided.
* Only after the in-memory representation is built, it is deserialized into a brand new configuration structure.

You can pass a structure that is used *before* the first config is loaded.

Now, given these things, what would you like it to do if you passed a structure? Certainly, passing a structure that is `Serialize` as another representation for the bottom layer, serialize it to toml internally and use that would be simple to implement. If you wanted something different, we would have to first figure out what that would do.

**Comment by j-a-m-l** [comment]
My idea was providing a `Struct` that contains the default configuration as the base / bottom layer (0), and allow users overriding it:

  0. Default configuration
  1. Have a file on any of the `config_default_paths`
  2. Pass explicitly a configuration to the CLI
  3. Use environment variables

Before starting with Spirit, I implemented that idea using the `config` crate with something like this:

```rust
#[derive(Debug, Deserialize, Serialize)]
pub struct Settings {
    setting1: u32
}

impl Default for Settings {
    fn default() -> Self {
        Self {
          setting1: 0
        }
    }
}

impl Settings {
    pub fn new(file: PathBuf) -> Result<Self, ConfigError> {
        // The default settings
        let mut config = Config::try_from(&Settings::default()).unwrap();

        if file.exists() {
            // Add settings from the file
            config.merge(File::with_name(&file.to_str().unwrap()))?;
        }

        // Add settings from environment variables
        config.merge(Environment::with_prefix("PROJECT").separator("_"))?;

        config.try_into()
    }
    ...
```

Maybe that's the reason why, to me, forcing the use of TOML on that first layer feels a little awkward, specially on projects that don't use it to store the configuration.

So, what would I propose? I'd allow passing a `Serialize` to `config_defaults`, but I'd try to avoid that intermediate TOML serialization because it wouldn't be necessary.

**Comment by vorner** [comment]
I see. Well, I was thinking about the layer 0 mostly as „baked in config file“. But the view as already decoded default struct is also valid, so yes, why not. Would you like to send a pull request, or should I have a look?

The intermediate transformation to TOML is probably not necessary, but I'd probably do it that way anyway, as it's less code and fewer corner cases (otherwise, the Spirit will have to keep either the textual version, the struct or nothing). And honestly, reloading configuration is such a rare action where performance doesn't really matter.

**Comment by j-a-m-l** [comment]
Thanks. I'd rather let you look at it since you're more familiar with the project and you could take decisions in case you prefer 1 approach over another.

**Comment by vorner** [comment]
Can you have a look at the typed-default-cfg branch, if this is somewhat the feature you want? Or even better test it?

**Comment by j-a-m-l** [comment]
Apart from those 2 comment, I've tried it and it's working flawlessly.

**Comment by vorner** [comment]
Thank you. I'll look at them and I expect to release next version with this included in few days, maybe over the weekend.
