### ISSUE TITLE
Unable to compile due to usage of non-public structopt API

### ISSUE THREAD

**Issue by Schuwi** [vorner/spirit#48]
Compilation of a fresh clone of this repository fails with:
```
   Compiling spirit v0.4.1
error[E0599]: no function or associated item named `augment_clap` found for type `cfg_loader::CommonOpts` in the current scope
  --> src/cfg_loader.rs:90:21
   |
64 | struct CommonOpts {
   | ----------------- function or associated item `augment_clap` not found for this
...
90 |         CommonOpts::augment_clap(O::clap())
   |                     ^^^^^^^^^^^^ function or associated item not found in `cfg_loader::CommonOpts`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use structopt::StructOptInternal;`

error: aborting due to previous error
```
(Also fails when using spirit as a dependency)

The `augment_clap` function seems to be non-public API of structopt and was changed in commit https://github.com/TeXitoi/structopt/commit/82485f202814d6469fe950dc0814424d2311929b [structopt v0.3.7].

I confirmed that spirit compiles fine when forcing cargo to use structopt v0.3.5 (v0.3.6 doesn't seem to be available on crates.io) with `cargo update -p structopt --precise 0.3.5`.

**Comment by vorner** [comment]
That's unfortunate :-(. Currently, I don't really have much energy and motivation working on spirit and making some part of API private seems like semver-incompatible change. Possibilities are:

* Bringing this up with structopt developers and asking what the proper way is.
* Someone, maybe you, discovers a new way how to combine the structopt structures that have generics on them.
* Locking the version of dependency onto the lower one (not really nice thing to do)
* Forking structopt (doesn't seem like a nice thing to do)

So, I'll leave it up to you for now ‒ I'll find the time to review and do releases, but really don't want to invest much more.

**Comment by Schuwi** [comment]
Thanks for the fast response!

As far as I can see that part of the API has never really been public in the first place but I could be wrong about that, I haven't dug too deep into this.
I honestly don't really use spirit, I only use spirit-log for it's AsyncLogger to use as a wrapper with fern so I won't move forward with this in any way and will just use the workaround of locking the dependency version in my build.

Either way I would definitely keep this issue open for reference and for anyone who might want to fix this in the future.

**Comment by vorner** [comment]
I've found a simple workaround for now, I'll release 0.4.2. But it's mostly just moving the problem further into the future, a proper solution needs to be found.
